// Ho Jin Choi — research portfolio data
window.SITE_DATA = {
  name: "Ho Jin Choi",
  headshot: "assets/headshot.jpg",
  role: "PhD Student in Robotics",
  affiliation: "University of Pennsylvania",
  lab: "Figueroa Robotics Lab",
  advisor: "Nadia Figueroa",
  advisorUrl: "https://nbfigueroa.github.io/",
  labUrl: "https://figueroa.seas.upenn.edu/",
  uniUrl: "https://www.upenn.edu/",
  bio: [
    "I am a PhD student in Robotics at the",
    { text: "University of Pennsylvania", url: "https://www.upenn.edu/" },
    ", working with",
    { text: "Nadia Figueroa ", url: "https://nbfigueroa.github.io/" },
    " in the",
    { text: "Figueroa Robotics Lab", url: "https://figueroa.seas.upenn.edu/" },
    ". I study tightly coupled perception and control for real-time robot intelligence, developing geometric and optimization-driven methods for 6D pose, visuotactile representation learning, and dynamic grasping. My goal is to build reactive systems that operate robustly in uncertain, dynamic environments.",
  ],
  status: "Looking for Collaborations!",
  contact: {
    email: "cr139139@seas.upenn.com",
    linkedin: "linkedin.com/in/ho-jin-choi-425856208",
    linkedinUrl: "https://linkedin.com/in/ho-jin-choi-425856208/",
    github: "github.com/cr139139",
    githubUrl: "https://github.com/cr139139",
    scholarUrl: "",
  },
  news: [
    { date: "Feb 2026", text: "COMETH published in ESWA." },
    { date: "Oct 2025", text: "SplatCtrl accepted to ICRA 2026." },
    { date: "Jun 2025", text: "Dynamic-ASM6D accepted to the RSS 2025 Workshop." },
  ],

  // Papers + projects unified. `kind` is "paper" or "project".
  // Ordered newest-first; the UI groups by year.
  items: [
    {
      kind: "paper",
      id: "dynamic-asm6d",
      title: "Dynamic-ASM6D: Real-time 6D Object Pose and Shape Estimation via Active Shape Models and ADMM",
      authors: ["H. Choi", "Y. Cheng", "M. Kim", "N. Figueroa"],
      venue: "RSS Workshop",
      year: "2025",
      badge: "RSS 2025 Workshop",
      thumb: "assets/papers/dynamic-asm6d.png",
      teaserAlt: "Real-time object pose and shape estimation",
      abstract: "A real-time approach to joint 6D pose and shape estimation for novel objects. We combine Active Shape Models with ADMM-based optimization to track non-rigid and partially-observed geometry at interactive rates suitable for reactive manipulation.",
      links: [
        { kind: "workshop", label: "workshop", url: "https://equisystems.github.io/" },
      ],
      bibtex: `@inproceedings{choi2025dynamicasm6d,
  title     = {Dynamic-ASM6D: Real-time 6D Object Pose and Shape Estimation via Active Shape Models and ADMM},
  author    = {Choi, H. and Cheng, Y. and Kim, M. and Figueroa, N.},
  booktitle = {RSS 2025 Workshop},
  year      = {2025}
}`,
    },
    {
      kind: "paper",
      id: "splatctrl",
      title: "SplatCtrl: Perception–Action Coupling via Gaussian Scene Representations and Reactive Robot Control",
      authors: ["S. Jain", "H. Choi"],
      venue: "ICRA",
      year: "2026",
      badge: "ICRA 2026",
      thumb: "assets/papers/splatctrl.png",
      teaserAlt: "Gaussian splatting scene with robot arm",
      abstract: "SplatCtrl couples a Gaussian scene representation directly to a reactive controller, letting the robot replan in real time as the scene updates. The perception–action loop is tight enough to handle moving obstacles and manipulation under changing illumination.",
      links: [
        { kind: "paper", label: "paper", url: "https://www.merl.com/publications/docs/TR2025-096.pdf" },
      ],
      bibtex: `@inproceedings{jain2026splatctrl,
  title     = {SplatCtrl: Perception--Action Coupling via Gaussian Scene Representations and Reactive Robot Control},
  author    = {Jain, S. and Choi, H.},
  booktitle = {IEEE International Conference on Robotics and Automation (ICRA)},
  year      = {2026}
}`,
    },
    {
      kind: "paper",
      id: "cometh",
      title: "COMETH: Convex Optimization for Multiview Estimation and Tracking of Humans",
      authors: ["E. Martini", "H. Choi", "N. Figueroa", "N. Bombieri"],
      venue: "Expert Systems with Applications",
      year: "2025",
      badge: "ESWA",
      thumb: "assets/papers/cometh.jpg",
      teaserAlt: "Multi-view human pose tracking",
      abstract: "A convex formulation for multi-view human body estimation and tracking. COMETH produces globally consistent 3D keypoints from noisy 2D detections across cameras, enabling robust real-time tracking in cluttered workspaces.",
      links: [
        { kind: "arxiv", label: "arXiv", url: "https://arxiv.org/abs/2508.20920v1" },
      ],
      bibtex: `@article{martini2025cometh,
  title   = {COMETH: Convex Optimization for Multiview Estimation and Tracking of Humans},
  author  = {Martini, E. and Choi, H. and Figueroa, N. and Bombieri, N.},
  journal = {Expert Systems with Applications},
  year    = {2025}
}`,
    },
    {
      kind: "paper",
      id: "dynamic-grasping",
      title: "Towards Feasible Dynamic Grasping: Leveraging Gaussian Process Distance Fields, SE(3) Equivariance and Riemannian Mixture Models",
      authors: ["H. Choi", "N. Figueroa"],
      venue: "ICRA",
      year: "2024",
      badge: "ICRA 2024",
      thumb: "assets/papers/dynamic-grasping.png",
      teaserAlt: "Dynamic grasping with GPDF",
      abstract: "Dynamic grasping under partial observability by combining Gaussian Process Distance Fields with SE(3)-equivariant policies and Riemannian Mixture Models. The system produces feasible, geometry-aware grasps that adapt as the scene evolves.",
      links: [
        { kind: "arxiv", label: "arXiv", url: "https://arxiv.org/abs/2311.02576" },
        { kind: "video", label: "video", url: "https://www.youtube.com/watch?v=wjIVrwTzTOc" },
      ],
      bibtex: `@inproceedings{choi2024dynamicgrasping,
  title     = {Towards Feasible Dynamic Grasping: Leveraging Gaussian Process Distance Fields, SE(3) Equivariance and Riemannian Mixture Models},
  author    = {Choi, H. and Figueroa, N.},
  booktitle = {IEEE International Conference on Robotics and Automation (ICRA)},
  year      = {2024}
}`,
    },
    {
      kind: "paper",
      id: "eeg-motor",
      title: "On the Feasibility of EEG-based Motor Intention Detection for Real-Time Robot Assistive Control",
      authors: ["H. Choi", "S. Das", "S. Peng", "R. Bajcsy", "N. Figueroa"],
      venue: "ICRA",
      year: "2024",
      badge: "ICRA 2024",
      thumb: "assets/papers/eeg-motor.png",
      teaserAlt: "EEG-based assistive robot control",
      abstract: "A feasibility study of EEG-based motor intention decoding as a real-time control signal for assistive robots. We characterize latency, reliability, and the interaction design implications for users who depend on assistive manipulation.",
      links: [
        { kind: "arxiv", label: "arXiv", url: "https://arxiv.org/abs/2403.08149" },
        { kind: "video", label: "video", url: "https://www.youtube.com/watch?v=NFpO8_4gKWQ" },
      ],
      bibtex: `@inproceedings{choi2024eeg,
  title     = {On the Feasibility of EEG-based Motor Intention Detection for Real-Time Robot Assistive Control},
  author    = {Choi, H. and Das, S. and Peng, S. and Bajcsy, R. and Figueroa, N.},
  booktitle = {IEEE International Conference on Robotics and Automation (ICRA)},
  year      = {2024}
}`,
    },
  ],
};
